"""Shared helpers: HTTP with retries, output paths, plotting style, README results injection."""
from __future__ import annotations

import pathlib
import re
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import requests  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent
DATA = ROOT / "data"
OUT = ROOT / "outputs"
FIG = OUT / "figures"

PALETTE = ["#2E5EAA", "#E07A2F", "#3A9D6B", "#C0392B", "#7D5BA6", "#8C6D46", "#D35D9B", "#5B6770"]
HIGHLIGHT = "#C0392B"
MUTED = "#B8BEC6"


def setup() -> None:
    for p in (DATA, FIG):
        p.mkdir(parents=True, exist_ok=True)
    plt.rcParams.update({
        "figure.figsize": (9, 5.5),
        "figure.dpi": 110,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "axes.titleweight": "bold",
        "axes.titlesize": 13,
        "axes.labelsize": 11,
        "axes.prop_cycle": plt.cycler(color=PALETTE),
        "legend.frameon": False,
        "font.family": "DejaVu Sans",
    })


def get(url: str, *, retries: int = 4, timeout: int = 120, **kw) -> requests.Response:
    """GET with exponential back-off. Raises on final failure."""
    headers = {"User-Agent": "Mozilla/5.0 (research script; github-actions)"}
    last = None
    for i in range(retries):
        try:
            r = requests.get(url, headers=headers, timeout=timeout, **kw)
            if r.status_code == 200:
                return r
            last = RuntimeError(f"HTTP {r.status_code} for {url}")
        except requests.RequestException as e:  # pragma: no cover - network
            last = e
        time.sleep(2 ** i)
    raise RuntimeError(f"Failed to fetch {url}: {last}")


def savefig(fig, name: str, source: str | None = None) -> str:
    if source:
        fig.text(0.01, -0.01, f"Source: {source}", fontsize=8, color="#666", ha="left", va="top")
    path = FIG / f"{name}.png"
    fig.savefig(path, dpi=160, bbox_inches="tight")
    plt.close(fig)
    return f"outputs/figures/{name}.png"


def md_table(df, floatfmt: str = "{:.2f}") -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, row in df.iterrows():
        cells = []
        for v in row:
            if isinstance(v, float):
                cells.append("–" if v != v else floatfmt.format(v))
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def write_results(md: str) -> None:
    """Write outputs/results.md and inject it into README between the RESULTS markers."""
    stamp = time.strftime("%Y-%m-%d")
    md = f"_Auto-generated by `run.py` on {stamp}. Numbers refresh whenever the pipeline re-runs._\n\n" + md
    (OUT / "results.md").write_text(md, encoding="utf-8")
    readme = ROOT / "README.md"
    txt = readme.read_text(encoding="utf-8")
    new = re.sub(r"(<!-- RESULTS:START -->).*?(<!-- RESULTS:END -->)",
                 lambda m: m.group(1) + "\n" + md + "\n" + m.group(2), txt, flags=re.S)
    readme.write_text(new, encoding="utf-8")
